<?php

namespace SprykerEco\Shared\UnzerApi;

/**
 * Declares global environment configuration keys. Do not use it for other class constants.
 */
interface UnzerApiConstants
{
    public const WEBHOOK_RESOURCE_URL = 'UNZERAPI:WEBHOOK_RESOURCE_URL';
    public const BASKET_RESOURCE_URL = 'UNZERAPI:BASKET_RESOURCE_URL';
    public const CUSTOMER_RESOURCE_URL = 'UNZERAPI:CUSTOMER_RESOURCE_URL';
    public const METADATA_RESOURCE_URL = 'UNZERAPI:METADATA_RESOURCE_URL';
    public const CREATE_PAYMENT_RESOURCE_URL = 'UNZERAPI:CREATE_PAYMENT_RESOURCE_URL';
    public const MARKETPLACE_CHARGE_URL = 'UNZERAPI:MARKETPLACE_CHARGE_URL';
    public const MARKETPLACE_CREDIT_CARD_CHARGE_URL = 'UNZERAPI:MARKETPLACE_CREDIT_CARD_CHARGE_URL';
    public const MARKETPLACE_AUTHORIZE_URL = 'UNZERAPI:MARKETPLACE_AUTHORIZE_URL';
    public const MARKETPLACE_GET_PAYMENT_URL = 'UNZERAPI:MARKETPLACE_GET_PAYMENT_URL';
}
